[project]
name = "dora-franka-mujoco"
version = "0.1.0"
authors = [{ name = "Your Name", email = "email@email.com" }]
description = "MuJoCo-based Franka Emika Panda robot simulation node for Dora"
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
    "dora-rs >= 0.3.9",
    "mujoco >= 3.1.6",
    "numpy >= 1.21.0",
    "pyarrow >= 14.0.1",
    "scipy >= 1.7.0",
    "huggingface_hub >= 0.16.0",
]

[dependency-groups]
dev = ["pytest >=8.1.1", "ruff >=0.9.1"]

[project.scripts]
dora-franka-mujoco = "dora_franka_mujoco.main:main"

[tool.ruff.lint]
extend-select = [
  "UP",   # Ruff's UP rule
  "PERF", # Ruff's PERF rule
  "RET",  # Ruff's RET rule
  "RSE",  # Ruff's RSE rule
  "NPY",  # Ruff's NPY rule
]